### PR TITLE
Fix Invalid Tab and Link components

### PR DESCRIPTION
**Pull request by aimiisme**
The following issues have been resolved: #46, #47 and #48. Since they are related, I decided to debug in the same branch. Most of the bugs occurred in the `navbar.js` and `EventCardFlip.js` files due to invalid link components.

### CODE REVIEW

**Comment by Sanjay-B** [comment]
Resolve branch conflicts and then, re-request my review. @aimiisme

**Comment by aimiisme** [comment]
> Looks good to me. However, I encountered an interesting bug where if you do `npm run dev` and then, head over to the dev site, the navbar reloads the same tab once before being able to move to the next page. i.e I click `Events`. I go to events. I click `About`. I reloads `Events` / current page and does not go to the `About` page. Let me know if you can reproduce this error.

I don't have such a case, when I try the tabs they work properly and no problem at all. Or maybe I misunderstood what you're saying? Can you send me a screenshot or screen recording of it?

**Review by Sanjay-B — APPROVED** [review]
Looks good to me.

**Comment by Sanjay-B** [comment]
> > Looks good to me. However, I encountered an interesting bug where if you do `npm run dev` and then, head over to the dev site, the navbar reloads the same tab once before being able to move to the next page. i.e I click `Events`. I go to events. I click `About`. I reloads `Events` / current page and does not go to the `About` page. Let me know if you can reproduce this error.
> 
> I don't have such a case, when I try the tabs they work properly and no problem at all. Or maybe I misunderstood what you're saying? Can you send me a screenshot or screen recording of it?

Following up on discord. @aimiisme

**Pull request merged**
