### PR TITLE
Bug Fixed (#31) Infinite Horizontal Wave

### PR DESCRIPTION
**Pull request by aimiisme**
Fixed the bug that causes the horizontal scroll on the wave animation in this new branch `bugfix/infinite_wave` - resolved the issue #31 and pull request #27 .

### CODE REVIEW

**Review by Sanjay-B — CHANGES_REQUESTED** [review]
Vertical scrolling still exists when it shouldn't. Also, gradients are typically use in material ui design. It's has to be a solid color. i.e the wave is a gradient. The color needs to be solid. So, not a gradient. Otherwise, everything looks really good!

**Comment by aimiisme** [comment]
@Sanjay-B @PremKSU I removed the gradient in wave svg, now it has solid color only.
Need help with vertical scroll bar, I have tried using `overflow: hidden` but it does not work

**Comment by Sanjay-B** [comment]
> @Sanjay-B @PremKSU I removed the gradient in wave svg, now it has solid color only.
> Need help with vertical scroll bar, I have tried using `overflow: hidden` but it does not work

Appreciate it. I'll take this over.

**Review by Sanjay-B — COMMENTED** [review]
LGTM so far.

**Comment by Sanjay-B** [comment]
I think I fixed this but, I have to double-check using a bigger monitor than my laptop. I will follow up here.

**Comment by PremKSU** [comment]
Still seeing the vertical scroll bar on my laptop
image
@Sanjay-B

**Comment by aimiisme** [comment]
Ive modified the easing and timing function of wave animation a bit. This change has nothing to do with the vertical scroll bar issue

**Comment by Sanjay-B** [comment]
> Still seeing the vertical scroll bar on my laptop

@PremKSU Honestly, it shouldn't break functionality and the severity of this bug is not enough for me to prevent another feature from merging into `dev`. I think that the better idea here is to add it to the sheets and then, revisit this when we have time and a deadline isn't in a week.

**Review by Sanjay-B — APPROVED** [review]
LGTM. I will be merging. The bug that this PR specifically targets has been fixed. Vertical scroll bar bug should be in a different Bugfix branch. Will follow up with @PremKSU on Tuesday Technical Standup.

**Pull request merged**
