### PR TITLE
Bugfix - Update actions to be secure

### PR DESCRIPTION
**Pull request by teamrocket77**
This PR has no functionality changes. the OSSF Github action will fail, if we don't get some of these things corrected.
Changes
---
- `frontend-actions` - updated action: `check-pr-labels-on-push-action, cypress-io/github-action, actions/upload-artifact`to use sha instead of task
- `gcr_deployment` updated actions: `actions/checkout, google-github-actions` to use sha
- `Dockerfile` - updated all lines referencing node to use SHA
- `build.yml` - this file will attempt to build the project on push and PR, it's so we can confirm that the app actually works without deploying it. In the future it'll be abstracted away to the deployment, job will call it (like a function)

Why is this necessary?
- Because Tag numbers can be added and deleted arbitrarily, and the SHA is a specific reference to the contents of the Github Action or Container. 

Change to `navbar.js` - looks like one of the changes needed to find and click on pages didn't make it into the the PR or Repo, it's being added here and the branch will be tested with the UI/UX tag

### CODE REVIEW

**Review by Sanjay-B — APPROVED** [review]
LGTM. Nice job.

**Review by Sanjay-B — APPROVED** [review]
LGTM.

**Comment by teamrocket77** [comment]
The new line added to the gitignore is just working for the patter `env.*` as opposed to being a `.env` file.

**Review by IsaacAlao — APPROVED** [review]
LGTM 👍

**Pull request merged**
