### PR TITLE
Implement Wave Animation to Landing Page

### PR DESCRIPTION
**Pull request by aimiisme**
Implemented the wave animation in landing page

### CODE REVIEW

**Comment by aimiisme** [comment]
I created `feature/wave_animation` branch from existing `feature/responsive_landing_page` branch, that's why 3 previous commits from `feature/responsive_landing_page` appeared here. Please review the latest commit "Implementing Wave Animation" only. Sorry about that, I can create a new branch and start a new pull request if it's necessary.

**Review by Sanjay-B — APPROVED** [review]
I increased the z-index for a button but, the rest looks good to me. Since this is mostly a non-breaking visual change, I think it's best if we merge this into `dev` once this pr (https://github.com/KSU-Google-DSC/Webapp/pull/24) is completed / lands.

**Comment by Sanjay-B** [comment]
I will correct these myself. And I will merge later today. Other than the conflicts, looks good to me.

**Comment by Sanjay-B** [comment]
Merge is blocked by https://github.com/KSU-Google-DSC/Webapp/issues/31 .

**Comment by Sanjay-B** [comment]
Update on https://github.com/KSU-Google-DSC/Webapp/pull/32 : I think we've fixed the issue but, I need to verify on a bigger screen to make sure that the scrollbar (vertical) is actually locked. I will follow up on here relatively soon. cc: @PremKSU , @theTechOwl

**Review by Sanjay-B — APPROVED** [review]
LGTM! Merging.

**Pull request merged**
