### PR TITLE
Add Dashboard & Default Authentication in Dev

### PR DESCRIPTION
**Pull request by Sanjay-B**
Implement Dashboard & Default Nav based on ``http://localhost:3000/dashboard/*``. 

Implement Credentials in Test (Defaults to Oauth in prod): Username: ``admin``, Password: ``admin``.

### CODE REVIEW

**Comment by teamrocket77** [comment]
I think it looks fantastic THANKS!

**Review by teamrocket77 — COMMENTED** [review]
LGTM

**Review by teamrocket77 — APPROVED** [review]

**Comment by teamrocket77** [comment]
if you wanna run the tests, just push here again

**Review by IsaacAlao — APPROVED** [review]
LGTM!

**Review by aimiisme — CHANGES_REQUESTED** [review]
I suggest adding some sample files under `./pages/dashboard/*` for others to use as starting points (i.e `./pages/dashboard/memberlist`). The URL after clicking each tab on the dashboard menu would be, for example, `http://localhost:3000/dashboard/memberlist` This will prevent people from creating new files for the dashboard tab randomly.

**Comment by aimiisme** [comment]
I added some sample files for each dashboard tab on the commit above, the filename matches with the `href` assigned to each tab and the URL is: `http://localhost:3000/dashboard/*` as we want it to be. However, I don't know how they work with the `session` (when I log out -> the session ends -> the main content should disappear with the Dashboard Menu and the user should be directed back to the `Landing Page`.)
cc: @Sanjay-B

**Review by johnnymcmike — APPROVED** [review]
LGTM to me :)

**Comment by Sanjay-B** [comment]
> I added some sample files for each dashboard tab on the commit above, the filename matches with the `href` assigned to each tab and the URL is: `http://localhost:3000/dashboard/*` as we want it to be. However, I don't know how they work with the `session` (when I log out -> the session ends -> the main content should disappear with the Dashboard Menu and the user should be directed back to the `Landing Page`.)
> cc: @Sanjay-B

Ignore the last reply. I misread the question. Sessions are persistent across pages based on the ``SessionProvider``. You should be able to use ``useSession`` and then, ``session.user`` to check if the user is logged in. Checking just the ``session`` object doesn't work because it contains states even when the user isn't logged in.

**Comment by Sanjay-B** [comment]
I am going to wait for @Aimi review and then, merge this into ``dev`` as part of RC1 that is coming up. Should be easier to build branches on top of this for future features.

**Review by aimiisme — APPROVED** [review]
LGTM. Please go ahead and merge into the `dev` branch as a part of `RC1`. Any further actions will be discussed within the next RC.

**Pull request merged**
